# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c5a22fefb020bf8b83e1ef255d82ce61d28c5864ffe2516a9a93703cc45c6d31110d228eb9eb32db093a79aafc1b299c0a0420b0876444295008e0f19f4ff21

test:
  secret_key_base: 40865420d5056761133fb53c8f7c161fd24d86f26cff5d3b9cb98479903e3a13413cd10eb05de2287c92af870ccb05195e2164da2b367a9957c483dcb84d07cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
